"""create users, idioms, user_idiom_progress tables

Revision ID: 569577219ad2
Revises: 
Create Date: 2026-09-15 13:03:28.149641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569577219ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idioms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phrase', sa.String(length=255), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=False),
    sa.Column('example_sentence', sa.Text(), nullable=False),
    sa.Column('topic', sa.Enum('education', 'environment', 'technology', 'relationships', 'work', 'travel', 'health', 'culture', name='topic'), nullable=False),
    sa.Column('difficulty', sa.Enum('easier', 'intermediate', 'advanced', name='difficulty'), nullable=False),
    sa.Column('translation_ru', sa.String(length=255), nullable=True),
    sa.Column('translation_kk', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idioms_topic'), 'idioms', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', name='userrole'), nullable=False),
    sa.Column('native_language', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_idiom_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('idiom_id', sa.Integer(), nullable=False),
    sa.Column('box_level', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idiom_id'], ['idioms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idiom_id', name='uq_user_idiom')
    )
    op.create_index(op.f('ix_user_idiom_progress_idiom_id'), 'user_idiom_progress', ['idiom_id'], unique=False)
    op.create_index(op.f('ix_user_idiom_progress_next_review_at'), 'user_idiom_progress', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_user_idiom_progress_user_id'), 'user_idiom_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_idiom_progress_user_id'), table_name='user_idiom_progress')
    op.drop_index(op.f('ix_user_idiom_progress_next_review_at'), table_name='user_idiom_progress')
    op.drop_index(op.f('ix_user_idiom_progress_idiom_id'), table_name='user_idiom_progress')
    op.drop_table('user_idiom_progress')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_idioms_topic'), table_name='idioms')
    op.drop_table('idioms')
    # ### end Alembic commands ###
